// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway/g_pubsub.proto

package com.teneasyChat.gateway;

public final class GPubsub {
  private GPubsub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PubSubMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gateway.PubSubMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 接收人clientId
     * </pre>
     *
     * <code>int64 target = 1;</code>
     * @return The target.
     */
    long getTarget();

    /**
     * <code>.api.common.Message msg = 2;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.api.common.Message msg = 2;</code>
     * @return The msg.
     */
    com.teneasyChat.api.common.CMessage.Message getMsg();
    /**
     * <code>.api.common.Message msg = 2;</code>
     */
    com.teneasyChat.api.common.CMessage.MessageOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code gateway.PubSubMessage}
   */
  public static final class PubSubMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gateway.PubSubMessage)
      PubSubMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PubSubMessage.newBuilder() to construct.
    private PubSubMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PubSubMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PubSubMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.gateway.GPubsub.internal_static_gateway_PubSubMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.gateway.GPubsub.internal_static_gateway_PubSubMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.gateway.GPubsub.PubSubMessage.class, com.teneasyChat.gateway.GPubsub.PubSubMessage.Builder.class);
    }

    public static final int TARGET_FIELD_NUMBER = 1;
    private long target_ = 0L;
    /**
     * <pre>
     * 接收人clientId
     * </pre>
     *
     * <code>int64 target = 1;</code>
     * @return The target.
     */
    @java.lang.Override
    public long getTarget() {
      return target_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.teneasyChat.api.common.CMessage.Message msg_;
    /**
     * <code>.api.common.Message msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.api.common.Message msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CMessage.Message getMsg() {
      return msg_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : msg_;
    }
    /**
     * <code>.api.common.Message msg = 2;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CMessage.MessageOrBuilder getMsgOrBuilder() {
      return msg_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (target_ != 0L) {
        output.writeInt64(1, target_);
      }
      if (msg_ != null) {
        output.writeMessage(2, getMsg());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (target_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, target_);
      }
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.gateway.GPubsub.PubSubMessage)) {
        return super.equals(obj);
      }
      com.teneasyChat.gateway.GPubsub.PubSubMessage other = (com.teneasyChat.gateway.GPubsub.PubSubMessage) obj;

      if (getTarget()
          != other.getTarget()) return false;
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTarget());
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.gateway.GPubsub.PubSubMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.gateway.GPubsub.PubSubMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gateway.PubSubMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gateway.PubSubMessage)
        com.teneasyChat.gateway.GPubsub.PubSubMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.gateway.GPubsub.internal_static_gateway_PubSubMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.gateway.GPubsub.internal_static_gateway_PubSubMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.gateway.GPubsub.PubSubMessage.class, com.teneasyChat.gateway.GPubsub.PubSubMessage.Builder.class);
      }

      // Construct using com.teneasyChat.gateway.GPubsub.PubSubMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        target_ = 0L;
        msg_ = null;
        if (msgBuilder_ != null) {
          msgBuilder_.dispose();
          msgBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.gateway.GPubsub.internal_static_gateway_PubSubMessage_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.gateway.GPubsub.PubSubMessage getDefaultInstanceForType() {
        return com.teneasyChat.gateway.GPubsub.PubSubMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.gateway.GPubsub.PubSubMessage build() {
        com.teneasyChat.gateway.GPubsub.PubSubMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.gateway.GPubsub.PubSubMessage buildPartial() {
        com.teneasyChat.gateway.GPubsub.PubSubMessage result = new com.teneasyChat.gateway.GPubsub.PubSubMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.gateway.GPubsub.PubSubMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.target_ = target_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msg_ = msgBuilder_ == null
              ? msg_
              : msgBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.gateway.GPubsub.PubSubMessage) {
          return mergeFrom((com.teneasyChat.gateway.GPubsub.PubSubMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.gateway.GPubsub.PubSubMessage other) {
        if (other == com.teneasyChat.gateway.GPubsub.PubSubMessage.getDefaultInstance()) return this;
        if (other.getTarget() != 0L) {
          setTarget(other.getTarget());
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                target_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getMsgFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long target_ ;
      /**
       * <pre>
       * 接收人clientId
       * </pre>
       *
       * <code>int64 target = 1;</code>
       * @return The target.
       */
      @java.lang.Override
      public long getTarget() {
        return target_;
      }
      /**
       * <pre>
       * 接收人clientId
       * </pre>
       *
       * <code>int64 target = 1;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(long value) {
        
        target_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收人clientId
       * </pre>
       *
       * <code>int64 target = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = 0L;
        onChanged();
        return this;
      }

      private com.teneasyChat.api.common.CMessage.Message msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder> msgBuilder_;
      /**
       * <code>.api.common.Message msg = 2;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       * @return The msg.
       */
      public com.teneasyChat.api.common.CMessage.Message getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public Builder setMsg(com.teneasyChat.api.common.CMessage.Message value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
        } else {
          msgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public Builder setMsg(
          com.teneasyChat.api.common.CMessage.Message.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public Builder mergeMsg(com.teneasyChat.api.common.CMessage.Message value) {
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            msg_ != null &&
            msg_ != com.teneasyChat.api.common.CMessage.Message.getDefaultInstance()) {
            getMsgBuilder().mergeFrom(value);
          } else {
            msg_ = value;
          }
        } else {
          msgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = null;
        if (msgBuilder_ != null) {
          msgBuilder_.dispose();
          msgBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public com.teneasyChat.api.common.CMessage.Message.Builder getMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      public com.teneasyChat.api.common.CMessage.MessageOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.api.common.Message msg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gateway.PubSubMessage)
    }

    // @@protoc_insertion_point(class_scope:gateway.PubSubMessage)
    private static final com.teneasyChat.gateway.GPubsub.PubSubMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.gateway.GPubsub.PubSubMessage();
    }

    public static com.teneasyChat.gateway.GPubsub.PubSubMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PubSubMessage>
        PARSER = new com.google.protobuf.AbstractParser<PubSubMessage>() {
      @java.lang.Override
      public PubSubMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PubSubMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PubSubMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.gateway.GPubsub.PubSubMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gateway_PubSubMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_PubSubMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026gateway/g_pubsub.proto\022\007gateway\032\032api/c" +
      "ommon/c_message.proto\"A\n\rPubSubMessage\022\016" +
      "\n\006target\030\001 \001(\003\022 \n\003msg\030\002 \001(\0132\023.api.common" +
      ".MessageB@\n\027com.teneasyChat.gatewayZ%wcs" +
      "/service/gateway/protocol;protocolb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.common.CMessage.getDescriptor(),
        });
    internal_static_gateway_PubSubMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gateway_PubSubMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gateway_PubSubMessage_descriptor,
        new java.lang.String[] { "Target", "Msg", });
    com.teneasyChat.api.common.CMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
