// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/asset/asset.proto

package com.teneasyChat.api.asset;

public final class AssetOuterClass {
  private AssetOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025api/asset/asset.proto\022\tapi.asset\032\033goog" +
      "le/protobuf/empty.proto\032\020api/option.prot" +
      "o2z\n\005Asset\022T\n\013Placeholder\022\026.google.proto" +
      "buf.Empty\032\026.google.protobuf.Empty\"\025\272\276\031\021\010" +
      "\350\007\322\014\013placeholder\032\033\272\276\031\027\272\006\005asset\312\014\002\001\020\322\014\007/a" +
      "ssetsBI\n\031com.teneasyChat.api.assetZ\023wcs/" +
      "api/asset;asset\272\276\031\025\242\006\005bland\262\006\n2022-12-10" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.teneasyChat.api.Option.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.teneasyChat.api.Option.info);
    registry.add(com.teneasyChat.api.Option.method);
    registry.add(com.teneasyChat.api.Option.service);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.teneasyChat.api.Option.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
