// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/core/chat.proto

package com.teneasyChat.api.core;

public final class ChatOuterClass {
  private ChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatListQueryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.ChatListQueryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    java.util.List<com.teneasyChat.api.common.CChat.ChatItem> 
        getChatsList();
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    com.teneasyChat.api.common.CChat.ChatItem getChats(int index);
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    int getChatsCount();
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    java.util.List<? extends com.teneasyChat.api.common.CChat.ChatItemOrBuilder> 
        getChatsOrBuilderList();
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    com.teneasyChat.api.common.CChat.ChatItemOrBuilder getChatsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 聊天会话列表
   * </pre>
   *
   * Protobuf type {@code api.core.ChatListQueryResponse}
   */
  public static final class ChatListQueryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.ChatListQueryResponse)
      ChatListQueryResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatListQueryResponse.newBuilder() to construct.
    private ChatListQueryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatListQueryResponse() {
      chats_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatListQueryResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatListQueryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatListQueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.class, com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.Builder.class);
    }

    public static final int CHATS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.teneasyChat.api.common.CChat.ChatItem> chats_;
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.teneasyChat.api.common.CChat.ChatItem> getChatsList() {
      return chats_;
    }
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.teneasyChat.api.common.CChat.ChatItemOrBuilder> 
        getChatsOrBuilderList() {
      return chats_;
    }
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    @java.lang.Override
    public int getChatsCount() {
      return chats_.size();
    }
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CChat.ChatItem getChats(int index) {
      return chats_.get(index);
    }
    /**
     * <code>repeated .api.common.ChatItem chats = 1;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CChat.ChatItemOrBuilder getChatsOrBuilder(
        int index) {
      return chats_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < chats_.size(); i++) {
        output.writeMessage(1, chats_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < chats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, chats_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse other = (com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse) obj;

      if (!getChatsList()
          .equals(other.getChatsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChatsCount() > 0) {
        hash = (37 * hash) + CHATS_FIELD_NUMBER;
        hash = (53 * hash) + getChatsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 聊天会话列表
     * </pre>
     *
     * Protobuf type {@code api.core.ChatListQueryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.ChatListQueryResponse)
        com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatListQueryResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatListQueryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.class, com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (chatsBuilder_ == null) {
          chats_ = java.util.Collections.emptyList();
        } else {
          chats_ = null;
          chatsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatListQueryResponse_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse getDefaultInstanceForType() {
        return com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse build() {
        com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse buildPartial() {
        com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse result = new com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse result) {
        if (chatsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            chats_ = java.util.Collections.unmodifiableList(chats_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.chats_ = chats_;
        } else {
          result.chats_ = chatsBuilder_.build();
        }
      }

      private void buildPartial0(com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse) {
          return mergeFrom((com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse other) {
        if (other == com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse.getDefaultInstance()) return this;
        if (chatsBuilder_ == null) {
          if (!other.chats_.isEmpty()) {
            if (chats_.isEmpty()) {
              chats_ = other.chats_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChatsIsMutable();
              chats_.addAll(other.chats_);
            }
            onChanged();
          }
        } else {
          if (!other.chats_.isEmpty()) {
            if (chatsBuilder_.isEmpty()) {
              chatsBuilder_.dispose();
              chatsBuilder_ = null;
              chats_ = other.chats_;
              bitField0_ = (bitField0_ & ~0x00000001);
              chatsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChatsFieldBuilder() : null;
            } else {
              chatsBuilder_.addAllMessages(other.chats_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.teneasyChat.api.common.CChat.ChatItem m =
                    input.readMessage(
                        com.teneasyChat.api.common.CChat.ChatItem.parser(),
                        extensionRegistry);
                if (chatsBuilder_ == null) {
                  ensureChatsIsMutable();
                  chats_.add(m);
                } else {
                  chatsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.teneasyChat.api.common.CChat.ChatItem> chats_ =
        java.util.Collections.emptyList();
      private void ensureChatsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          chats_ = new java.util.ArrayList<com.teneasyChat.api.common.CChat.ChatItem>(chats_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.teneasyChat.api.common.CChat.ChatItem, com.teneasyChat.api.common.CChat.ChatItem.Builder, com.teneasyChat.api.common.CChat.ChatItemOrBuilder> chatsBuilder_;

      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public java.util.List<com.teneasyChat.api.common.CChat.ChatItem> getChatsList() {
        if (chatsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(chats_);
        } else {
          return chatsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public int getChatsCount() {
        if (chatsBuilder_ == null) {
          return chats_.size();
        } else {
          return chatsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public com.teneasyChat.api.common.CChat.ChatItem getChats(int index) {
        if (chatsBuilder_ == null) {
          return chats_.get(index);
        } else {
          return chatsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder setChats(
          int index, com.teneasyChat.api.common.CChat.ChatItem value) {
        if (chatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatsIsMutable();
          chats_.set(index, value);
          onChanged();
        } else {
          chatsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder setChats(
          int index, com.teneasyChat.api.common.CChat.ChatItem.Builder builderForValue) {
        if (chatsBuilder_ == null) {
          ensureChatsIsMutable();
          chats_.set(index, builderForValue.build());
          onChanged();
        } else {
          chatsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder addChats(com.teneasyChat.api.common.CChat.ChatItem value) {
        if (chatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatsIsMutable();
          chats_.add(value);
          onChanged();
        } else {
          chatsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder addChats(
          int index, com.teneasyChat.api.common.CChat.ChatItem value) {
        if (chatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatsIsMutable();
          chats_.add(index, value);
          onChanged();
        } else {
          chatsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder addChats(
          com.teneasyChat.api.common.CChat.ChatItem.Builder builderForValue) {
        if (chatsBuilder_ == null) {
          ensureChatsIsMutable();
          chats_.add(builderForValue.build());
          onChanged();
        } else {
          chatsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder addChats(
          int index, com.teneasyChat.api.common.CChat.ChatItem.Builder builderForValue) {
        if (chatsBuilder_ == null) {
          ensureChatsIsMutable();
          chats_.add(index, builderForValue.build());
          onChanged();
        } else {
          chatsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder addAllChats(
          java.lang.Iterable<? extends com.teneasyChat.api.common.CChat.ChatItem> values) {
        if (chatsBuilder_ == null) {
          ensureChatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, chats_);
          onChanged();
        } else {
          chatsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder clearChats() {
        if (chatsBuilder_ == null) {
          chats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          chatsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public Builder removeChats(int index) {
        if (chatsBuilder_ == null) {
          ensureChatsIsMutable();
          chats_.remove(index);
          onChanged();
        } else {
          chatsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public com.teneasyChat.api.common.CChat.ChatItem.Builder getChatsBuilder(
          int index) {
        return getChatsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public com.teneasyChat.api.common.CChat.ChatItemOrBuilder getChatsOrBuilder(
          int index) {
        if (chatsBuilder_ == null) {
          return chats_.get(index);  } else {
          return chatsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public java.util.List<? extends com.teneasyChat.api.common.CChat.ChatItemOrBuilder> 
           getChatsOrBuilderList() {
        if (chatsBuilder_ != null) {
          return chatsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(chats_);
        }
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public com.teneasyChat.api.common.CChat.ChatItem.Builder addChatsBuilder() {
        return getChatsFieldBuilder().addBuilder(
            com.teneasyChat.api.common.CChat.ChatItem.getDefaultInstance());
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public com.teneasyChat.api.common.CChat.ChatItem.Builder addChatsBuilder(
          int index) {
        return getChatsFieldBuilder().addBuilder(
            index, com.teneasyChat.api.common.CChat.ChatItem.getDefaultInstance());
      }
      /**
       * <code>repeated .api.common.ChatItem chats = 1;</code>
       */
      public java.util.List<com.teneasyChat.api.common.CChat.ChatItem.Builder> 
           getChatsBuilderList() {
        return getChatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.teneasyChat.api.common.CChat.ChatItem, com.teneasyChat.api.common.CChat.ChatItem.Builder, com.teneasyChat.api.common.CChat.ChatItemOrBuilder> 
          getChatsFieldBuilder() {
        if (chatsBuilder_ == null) {
          chatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.teneasyChat.api.common.CChat.ChatItem, com.teneasyChat.api.common.CChat.ChatItem.Builder, com.teneasyChat.api.common.CChat.ChatItemOrBuilder>(
                  chats_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          chats_ = null;
        }
        return chatsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.ChatListQueryResponse)
    }

    // @@protoc_insertion_point(class_scope:api.core.ChatListQueryResponse)
    private static final com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse();
    }

    public static com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatListQueryResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChatListQueryResponse>() {
      @java.lang.Override
      public ChatListQueryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatListQueryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatListQueryResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.ChatOuterClass.ChatListQueryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatMarkReadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.ChatMarkReadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
     * @return The chatId.
     */
    long getChatId();
  }
  /**
   * <pre>
   * 标记已读
   * </pre>
   *
   * Protobuf type {@code api.core.ChatMarkReadRequest}
   */
  public static final class ChatMarkReadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.ChatMarkReadRequest)
      ChatMarkReadRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMarkReadRequest.newBuilder() to construct.
    private ChatMarkReadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMarkReadRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMarkReadRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatMarkReadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatMarkReadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.class, com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.Builder.class);
    }

    public static final int CHAT_ID_FIELD_NUMBER = 1;
    private long chatId_ = 0L;
    /**
     * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatId_ != 0L) {
        output.writeInt64(1, chatId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, chatId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest other = (com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest) obj;

      if (getChatId()
          != other.getChatId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 标记已读
     * </pre>
     *
     * Protobuf type {@code api.core.ChatMarkReadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.ChatMarkReadRequest)
        com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatMarkReadRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatMarkReadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.class, com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        chatId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_ChatMarkReadRequest_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest getDefaultInstanceForType() {
        return com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest build() {
        com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest buildPartial() {
        com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest result = new com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.chatId_ = chatId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest) {
          return mergeFrom((com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest other) {
        if (other == com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest.getDefaultInstance()) return this;
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                chatId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long chatId_ ;
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @return The chatId.
       */
      @java.lang.Override
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {
        
        chatId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chatId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.ChatMarkReadRequest)
    }

    // @@protoc_insertion_point(class_scope:api.core.ChatMarkReadRequest)
    private static final com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest();
    }

    public static com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMarkReadRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChatMarkReadRequest>() {
      @java.lang.Override
      public ChatMarkReadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMarkReadRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMarkReadRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.ChatOuterClass.ChatMarkReadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrphanResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.OrphanResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 worker_id = 1;</code>
     * @return The workerId.
     */
    int getWorkerId();

    /**
     * <code>string nick = 2;</code>
     * @return The nick.
     */
    java.lang.String getNick();
    /**
     * <code>string nick = 2;</code>
     * @return The bytes for nick.
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    java.lang.String getAvatar();
    /**
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    com.google.protobuf.ByteString
        getAvatarBytes();
  }
  /**
   * Protobuf type {@code api.core.OrphanResponse}
   */
  public static final class OrphanResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.OrphanResponse)
      OrphanResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrphanResponse.newBuilder() to construct.
    private OrphanResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrphanResponse() {
      nick_ = "";
      avatar_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrphanResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_OrphanResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_OrphanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.class, com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.Builder.class);
    }

    public static final int WORKER_ID_FIELD_NUMBER = 1;
    private int workerId_ = 0;
    /**
     * <code>int32 worker_id = 1;</code>
     * @return The workerId.
     */
    @java.lang.Override
    public int getWorkerId() {
      return workerId_;
    }

    public static final int NICK_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nick_ = "";
    /**
     * <code>string nick = 2;</code>
     * @return The nick.
     */
    @java.lang.Override
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <code>string nick = 2;</code>
     * @return The bytes for nick.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object avatar_ = "";
    /**
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    @java.lang.Override
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (workerId_ != 0) {
        output.writeInt32(1, workerId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nick_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nick_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (workerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, workerId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nick_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nick_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.ChatOuterClass.OrphanResponse)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.ChatOuterClass.OrphanResponse other = (com.teneasyChat.api.core.ChatOuterClass.OrphanResponse) obj;

      if (getWorkerId()
          != other.getWorkerId()) return false;
      if (!getNick()
          .equals(other.getNick())) return false;
      if (!getAvatar()
          .equals(other.getAvatar())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId();
      hash = (37 * hash) + NICK_FIELD_NUMBER;
      hash = (53 * hash) + getNick().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.ChatOuterClass.OrphanResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.core.OrphanResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.OrphanResponse)
        com.teneasyChat.api.core.ChatOuterClass.OrphanResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_OrphanResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_OrphanResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.class, com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        workerId_ = 0;
        nick_ = "";
        avatar_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_OrphanResponse_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.OrphanResponse getDefaultInstanceForType() {
        return com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.OrphanResponse build() {
        com.teneasyChat.api.core.ChatOuterClass.OrphanResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.OrphanResponse buildPartial() {
        com.teneasyChat.api.core.ChatOuterClass.OrphanResponse result = new com.teneasyChat.api.core.ChatOuterClass.OrphanResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.ChatOuterClass.OrphanResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.workerId_ = workerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nick_ = nick_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.avatar_ = avatar_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.ChatOuterClass.OrphanResponse) {
          return mergeFrom((com.teneasyChat.api.core.ChatOuterClass.OrphanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.ChatOuterClass.OrphanResponse other) {
        if (other == com.teneasyChat.api.core.ChatOuterClass.OrphanResponse.getDefaultInstance()) return this;
        if (other.getWorkerId() != 0) {
          setWorkerId(other.getWorkerId());
        }
        if (!other.getNick().isEmpty()) {
          nick_ = other.nick_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                workerId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                nick_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                avatar_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int workerId_ ;
      /**
       * <code>int32 worker_id = 1;</code>
       * @return The workerId.
       */
      @java.lang.Override
      public int getWorkerId() {
        return workerId_;
      }
      /**
       * <code>int32 worker_id = 1;</code>
       * @param value The workerId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerId(int value) {
        
        workerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 worker_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        workerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nick_ = "";
      /**
       * <code>string nick = 2;</code>
       * @return The nick.
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nick = 2;</code>
       * @return The bytes for nick.
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nick = 2;</code>
       * @param value The nick to set.
       * @return This builder for chaining.
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNick() {
        nick_ = getDefaultInstance().getNick();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 2;</code>
       * @param value The bytes for nick to set.
       * @return This builder for chaining.
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nick_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <code>string avatar = 3;</code>
       * @return The avatar.
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar = 3;</code>
       * @return The bytes for avatar.
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar = 3;</code>
       * @param value The avatar to set.
       * @return This builder for chaining.
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        avatar_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvatar() {
        avatar_ = getDefaultInstance().getAvatar();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       * @param value The bytes for avatar to set.
       * @return This builder for chaining.
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        avatar_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.OrphanResponse)
    }

    // @@protoc_insertion_point(class_scope:api.core.OrphanResponse)
    private static final com.teneasyChat.api.core.ChatOuterClass.OrphanResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.ChatOuterClass.OrphanResponse();
    }

    public static com.teneasyChat.api.core.ChatOuterClass.OrphanResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrphanResponse>
        PARSER = new com.google.protobuf.AbstractParser<OrphanResponse>() {
      @java.lang.Override
      public OrphanResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrphanResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrphanResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.ChatOuterClass.OrphanResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MarkRepliedRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.MarkRepliedRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
     * @return The chatId.
     */
    long getChatId();
  }
  /**
   * Protobuf type {@code api.core.MarkRepliedRequest}
   */
  public static final class MarkRepliedRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.MarkRepliedRequest)
      MarkRepliedRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarkRepliedRequest.newBuilder() to construct.
    private MarkRepliedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarkRepliedRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MarkRepliedRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_MarkRepliedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_MarkRepliedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.class, com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.Builder.class);
    }

    public static final int CHAT_ID_FIELD_NUMBER = 1;
    private long chatId_ = 0L;
    /**
     * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatId_ != 0L) {
        output.writeInt64(1, chatId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, chatId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest other = (com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest) obj;

      if (getChatId()
          != other.getChatId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChatId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.core.MarkRepliedRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.MarkRepliedRequest)
        com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_MarkRepliedRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_MarkRepliedRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.class, com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        chatId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.ChatOuterClass.internal_static_api_core_MarkRepliedRequest_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest getDefaultInstanceForType() {
        return com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest build() {
        com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest buildPartial() {
        com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest result = new com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.chatId_ = chatId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest) {
          return mergeFrom((com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest other) {
        if (other == com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest.getDefaultInstance()) return this;
        if (other.getChatId() != 0L) {
          setChatId(other.getChatId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                chatId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long chatId_ ;
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @return The chatId.
       */
      @java.lang.Override
      public long getChatId() {
        return chatId_;
      }
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @param value The chatId to set.
       * @return This builder for chaining.
       */
      public Builder setChatId(long value) {
        
        chatId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chat_id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearChatId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chatId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.MarkRepliedRequest)
    }

    // @@protoc_insertion_point(class_scope:api.core.MarkRepliedRequest)
    private static final com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest();
    }

    public static com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkRepliedRequest>
        PARSER = new com.google.protobuf.AbstractParser<MarkRepliedRequest>() {
      @java.lang.Override
      public MarkRepliedRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MarkRepliedRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkRepliedRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.ChatOuterClass.MarkRepliedRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_ChatListQueryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_ChatListQueryResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_ChatMarkReadRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_ChatMarkReadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_OrphanResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_OrphanResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_MarkRepliedRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_MarkRepliedRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023api/core/chat.proto\022\010api.core\032\033google/" +
      "protobuf/empty.proto\032\037google/protobuf/ti" +
      "mestamp.proto\032\027validate/validate.proto\032\020" +
      "api/option.proto\032\031api/common/c_worker.pr" +
      "oto\032\032api/common/c_message.proto\032\027api/com" +
      "mon/c_chat.proto\032\024api/core/front.proto\"<" +
      "\n\025ChatListQueryResponse\022#\n\005chats\030\001 \003(\0132\024" +
      ".api.common.ChatItem\"/\n\023ChatMarkReadRequ" +
      "est\022\030\n\007chat_id\030\001 \001(\003B\007\372B\004\"\002 \000\"A\n\016OrphanR" +
      "esponse\022\021\n\tworker_id\030\001 \001(\005\022\014\n\004nick\030\002 \001(\t" +
      "\022\016\n\006avatar\030\003 \001(\t\".\n\022MarkRepliedRequest\022\030" +
      "\n\007chat_id\030\001 \001(\003B\007\372B\004\"\002 \0002\262\004\n\004Chat\022`\n\005Que" +
      "ry\022\026.google.protobuf.Empty\032\037.api.core.Ch" +
      "atListQueryResponse\"\036\272\276\031\032\010\350\007\030\001\262\006\n2023-01" +
      "-02\322\014\005query\022e\n\010MarkRead\022\035.api.core.ChatM" +
      "arkReadRequest\032\026.google.protobuf.Empty\"\"" +
      "\272\276\031\036\010\351\007\030\001\262\006\n2023-01-02\322\014\tmark-read\022_\n\006Or" +
      "phan\022\026.google.protobuf.Empty\032\030.api.core." +
      "OrphanResponse\"#\272\276\031\037\010\352\007\030\001\262\006\n2023-01-17\312\014" +
      "\001\004\322\014\006orphan\022n\n\013MarkReplied\022\034.api.core.Ma" +
      "rkRepliedRequest\032\026.google.protobuf.Empty" +
      "\")\272\276\031%\010\353\007\030\001\262\006\n2023-02-03\312\014\001\004\322\014\014mark-repl" +
      "ied\022o\n\016ResetChatState\022\026.google.protobuf." +
      "Empty\032\026.google.protobuf.Empty\"-\272\276\031)\010\354\007\030\001" +
      "\262\006\n2023-02-15\312\014\001\004\322\014\020reset-chat-state\032\037\272\276" +
      "\031\033\272\006\004chat\312\014\002\020\004\322\014\014/tenant/chatBE\n\030com.ten" +
      "easyChat.api.coreZ\021wcs/api/core;core\272\276\031\024" +
      "\242\006\004jeff\262\006\n2023-01-02b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.teneasyChat.api.Option.getDescriptor(),
          com.teneasyChat.api.common.CWorker.getDescriptor(),
          com.teneasyChat.api.common.CMessage.getDescriptor(),
          com.teneasyChat.api.common.CChat.getDescriptor(),
          com.teneasyChat.api.core.FrontOuterClass.getDescriptor(),
        });
    internal_static_api_core_ChatListQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_core_ChatListQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_ChatListQueryResponse_descriptor,
        new java.lang.String[] { "Chats", });
    internal_static_api_core_ChatMarkReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_core_ChatMarkReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_ChatMarkReadRequest_descriptor,
        new java.lang.String[] { "ChatId", });
    internal_static_api_core_OrphanResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_core_OrphanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_OrphanResponse_descriptor,
        new java.lang.String[] { "WorkerId", "Nick", "Avatar", });
    internal_static_api_core_MarkRepliedRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_core_MarkRepliedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_MarkRepliedRequest_descriptor,
        new java.lang.String[] { "ChatId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.teneasyChat.api.Option.info);
    registry.add(com.teneasyChat.api.Option.method);
    registry.add(com.teneasyChat.api.Option.service);
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.teneasyChat.api.Option.getDescriptor();
    com.teneasyChat.api.common.CWorker.getDescriptor();
    com.teneasyChat.api.common.CMessage.getDescriptor();
    com.teneasyChat.api.common.CChat.getDescriptor();
    com.teneasyChat.api.core.FrontOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
