// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/core/metric.proto

package com.teneasyChat.api.core;

public final class MetricOuterClass {
  private MetricOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WorkerMetricOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.WorkerMetric)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 3分钟回复率, 万分比
     * 即: 9950 = 99.50%
     * </pre>
     *
     * <code>int32 reply_percent_3_min = 1;</code>
     * @return The replyPercent3Min.
     */
    int getReplyPercent3Min();

    /**
     * <pre>
     * 今日咨询人数
     * </pre>
     *
     * <code>int32 today_service = 2;</code>
     * @return The todayService.
     */
    int getTodayService();

    /**
     * <pre>
     * 平均响应时长
     * </pre>
     *
     * <code>int32 avg_reply_interval = 3;</code>
     * @return The avgReplyInterval.
     */
    int getAvgReplyInterval();

    /**
     * <pre>
     * 转任务数
     * </pre>
     *
     * <code>int32 transfer_to = 4;</code>
     * @return The transferTo.
     */
    int getTransferTo();

    /**
     * <pre>
     * 接任务数
     * </pre>
     *
     * <code>int32 transfer_from = 5;</code>
     * @return The transferFrom.
     */
    int getTransferFrom();
  }
  /**
   * <pre>
   * 客服指标
   * </pre>
   *
   * Protobuf type {@code api.core.WorkerMetric}
   */
  public static final class WorkerMetric extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.WorkerMetric)
      WorkerMetricOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WorkerMetric.newBuilder() to construct.
    private WorkerMetric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WorkerMetric() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WorkerMetric();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_WorkerMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_WorkerMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.class, com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder.class);
    }

    public static final int REPLY_PERCENT_3_MIN_FIELD_NUMBER = 1;
    private int replyPercent3Min_ = 0;
    /**
     * <pre>
     * 3分钟回复率, 万分比
     * 即: 9950 = 99.50%
     * </pre>
     *
     * <code>int32 reply_percent_3_min = 1;</code>
     * @return The replyPercent3Min.
     */
    @java.lang.Override
    public int getReplyPercent3Min() {
      return replyPercent3Min_;
    }

    public static final int TODAY_SERVICE_FIELD_NUMBER = 2;
    private int todayService_ = 0;
    /**
     * <pre>
     * 今日咨询人数
     * </pre>
     *
     * <code>int32 today_service = 2;</code>
     * @return The todayService.
     */
    @java.lang.Override
    public int getTodayService() {
      return todayService_;
    }

    public static final int AVG_REPLY_INTERVAL_FIELD_NUMBER = 3;
    private int avgReplyInterval_ = 0;
    /**
     * <pre>
     * 平均响应时长
     * </pre>
     *
     * <code>int32 avg_reply_interval = 3;</code>
     * @return The avgReplyInterval.
     */
    @java.lang.Override
    public int getAvgReplyInterval() {
      return avgReplyInterval_;
    }

    public static final int TRANSFER_TO_FIELD_NUMBER = 4;
    private int transferTo_ = 0;
    /**
     * <pre>
     * 转任务数
     * </pre>
     *
     * <code>int32 transfer_to = 4;</code>
     * @return The transferTo.
     */
    @java.lang.Override
    public int getTransferTo() {
      return transferTo_;
    }

    public static final int TRANSFER_FROM_FIELD_NUMBER = 5;
    private int transferFrom_ = 0;
    /**
     * <pre>
     * 接任务数
     * </pre>
     *
     * <code>int32 transfer_from = 5;</code>
     * @return The transferFrom.
     */
    @java.lang.Override
    public int getTransferFrom() {
      return transferFrom_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (replyPercent3Min_ != 0) {
        output.writeInt32(1, replyPercent3Min_);
      }
      if (todayService_ != 0) {
        output.writeInt32(2, todayService_);
      }
      if (avgReplyInterval_ != 0) {
        output.writeInt32(3, avgReplyInterval_);
      }
      if (transferTo_ != 0) {
        output.writeInt32(4, transferTo_);
      }
      if (transferFrom_ != 0) {
        output.writeInt32(5, transferFrom_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (replyPercent3Min_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, replyPercent3Min_);
      }
      if (todayService_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, todayService_);
      }
      if (avgReplyInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, avgReplyInterval_);
      }
      if (transferTo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, transferTo_);
      }
      if (transferFrom_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, transferFrom_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.MetricOuterClass.WorkerMetric)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.MetricOuterClass.WorkerMetric other = (com.teneasyChat.api.core.MetricOuterClass.WorkerMetric) obj;

      if (getReplyPercent3Min()
          != other.getReplyPercent3Min()) return false;
      if (getTodayService()
          != other.getTodayService()) return false;
      if (getAvgReplyInterval()
          != other.getAvgReplyInterval()) return false;
      if (getTransferTo()
          != other.getTransferTo()) return false;
      if (getTransferFrom()
          != other.getTransferFrom()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLY_PERCENT_3_MIN_FIELD_NUMBER;
      hash = (53 * hash) + getReplyPercent3Min();
      hash = (37 * hash) + TODAY_SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getTodayService();
      hash = (37 * hash) + AVG_REPLY_INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getAvgReplyInterval();
      hash = (37 * hash) + TRANSFER_TO_FIELD_NUMBER;
      hash = (53 * hash) + getTransferTo();
      hash = (37 * hash) + TRANSFER_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getTransferFrom();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.MetricOuterClass.WorkerMetric prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 客服指标
     * </pre>
     *
     * Protobuf type {@code api.core.WorkerMetric}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.WorkerMetric)
        com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_WorkerMetric_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_WorkerMetric_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.class, com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        replyPercent3Min_ = 0;
        todayService_ = 0;
        avgReplyInterval_ = 0;
        transferTo_ = 0;
        transferFrom_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_WorkerMetric_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getDefaultInstanceForType() {
        return com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric build() {
        com.teneasyChat.api.core.MetricOuterClass.WorkerMetric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric buildPartial() {
        com.teneasyChat.api.core.MetricOuterClass.WorkerMetric result = new com.teneasyChat.api.core.MetricOuterClass.WorkerMetric(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.MetricOuterClass.WorkerMetric result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.replyPercent3Min_ = replyPercent3Min_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.todayService_ = todayService_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.avgReplyInterval_ = avgReplyInterval_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.transferTo_ = transferTo_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.transferFrom_ = transferFrom_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.MetricOuterClass.WorkerMetric) {
          return mergeFrom((com.teneasyChat.api.core.MetricOuterClass.WorkerMetric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.MetricOuterClass.WorkerMetric other) {
        if (other == com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance()) return this;
        if (other.getReplyPercent3Min() != 0) {
          setReplyPercent3Min(other.getReplyPercent3Min());
        }
        if (other.getTodayService() != 0) {
          setTodayService(other.getTodayService());
        }
        if (other.getAvgReplyInterval() != 0) {
          setAvgReplyInterval(other.getAvgReplyInterval());
        }
        if (other.getTransferTo() != 0) {
          setTransferTo(other.getTransferTo());
        }
        if (other.getTransferFrom() != 0) {
          setTransferFrom(other.getTransferFrom());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                replyPercent3Min_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                todayService_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                avgReplyInterval_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                transferTo_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                transferFrom_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int replyPercent3Min_ ;
      /**
       * <pre>
       * 3分钟回复率, 万分比
       * 即: 9950 = 99.50%
       * </pre>
       *
       * <code>int32 reply_percent_3_min = 1;</code>
       * @return The replyPercent3Min.
       */
      @java.lang.Override
      public int getReplyPercent3Min() {
        return replyPercent3Min_;
      }
      /**
       * <pre>
       * 3分钟回复率, 万分比
       * 即: 9950 = 99.50%
       * </pre>
       *
       * <code>int32 reply_percent_3_min = 1;</code>
       * @param value The replyPercent3Min to set.
       * @return This builder for chaining.
       */
      public Builder setReplyPercent3Min(int value) {
        
        replyPercent3Min_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 3分钟回复率, 万分比
       * 即: 9950 = 99.50%
       * </pre>
       *
       * <code>int32 reply_percent_3_min = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyPercent3Min() {
        bitField0_ = (bitField0_ & ~0x00000001);
        replyPercent3Min_ = 0;
        onChanged();
        return this;
      }

      private int todayService_ ;
      /**
       * <pre>
       * 今日咨询人数
       * </pre>
       *
       * <code>int32 today_service = 2;</code>
       * @return The todayService.
       */
      @java.lang.Override
      public int getTodayService() {
        return todayService_;
      }
      /**
       * <pre>
       * 今日咨询人数
       * </pre>
       *
       * <code>int32 today_service = 2;</code>
       * @param value The todayService to set.
       * @return This builder for chaining.
       */
      public Builder setTodayService(int value) {
        
        todayService_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 今日咨询人数
       * </pre>
       *
       * <code>int32 today_service = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTodayService() {
        bitField0_ = (bitField0_ & ~0x00000002);
        todayService_ = 0;
        onChanged();
        return this;
      }

      private int avgReplyInterval_ ;
      /**
       * <pre>
       * 平均响应时长
       * </pre>
       *
       * <code>int32 avg_reply_interval = 3;</code>
       * @return The avgReplyInterval.
       */
      @java.lang.Override
      public int getAvgReplyInterval() {
        return avgReplyInterval_;
      }
      /**
       * <pre>
       * 平均响应时长
       * </pre>
       *
       * <code>int32 avg_reply_interval = 3;</code>
       * @param value The avgReplyInterval to set.
       * @return This builder for chaining.
       */
      public Builder setAvgReplyInterval(int value) {
        
        avgReplyInterval_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 平均响应时长
       * </pre>
       *
       * <code>int32 avg_reply_interval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgReplyInterval() {
        bitField0_ = (bitField0_ & ~0x00000004);
        avgReplyInterval_ = 0;
        onChanged();
        return this;
      }

      private int transferTo_ ;
      /**
       * <pre>
       * 转任务数
       * </pre>
       *
       * <code>int32 transfer_to = 4;</code>
       * @return The transferTo.
       */
      @java.lang.Override
      public int getTransferTo() {
        return transferTo_;
      }
      /**
       * <pre>
       * 转任务数
       * </pre>
       *
       * <code>int32 transfer_to = 4;</code>
       * @param value The transferTo to set.
       * @return This builder for chaining.
       */
      public Builder setTransferTo(int value) {
        
        transferTo_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 转任务数
       * </pre>
       *
       * <code>int32 transfer_to = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransferTo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        transferTo_ = 0;
        onChanged();
        return this;
      }

      private int transferFrom_ ;
      /**
       * <pre>
       * 接任务数
       * </pre>
       *
       * <code>int32 transfer_from = 5;</code>
       * @return The transferFrom.
       */
      @java.lang.Override
      public int getTransferFrom() {
        return transferFrom_;
      }
      /**
       * <pre>
       * 接任务数
       * </pre>
       *
       * <code>int32 transfer_from = 5;</code>
       * @param value The transferFrom to set.
       * @return This builder for chaining.
       */
      public Builder setTransferFrom(int value) {
        
        transferFrom_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接任务数
       * </pre>
       *
       * <code>int32 transfer_from = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransferFrom() {
        bitField0_ = (bitField0_ & ~0x00000010);
        transferFrom_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.WorkerMetric)
    }

    // @@protoc_insertion_point(class_scope:api.core.WorkerMetric)
    private static final com.teneasyChat.api.core.MetricOuterClass.WorkerMetric DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.MetricOuterClass.WorkerMetric();
    }

    public static com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WorkerMetric>
        PARSER = new com.google.protobuf.AbstractParser<WorkerMetric>() {
      @java.lang.Override
      public WorkerMetric parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WorkerMetric> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkerMetric> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuerySelfResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.core.QuerySelfResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     * @return Whether the metric field is set.
     */
    boolean hasMetric();
    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     * @return The metric.
     */
    com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getMetric();
    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     */
    com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder getMetricOrBuilder();
  }
  /**
   * Protobuf type {@code api.core.QuerySelfResponse}
   */
  public static final class QuerySelfResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.core.QuerySelfResponse)
      QuerySelfResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuerySelfResponse.newBuilder() to construct.
    private QuerySelfResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuerySelfResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuerySelfResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_QuerySelfResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_QuerySelfResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.class, com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.Builder.class);
    }

    public static final int METRIC_FIELD_NUMBER = 1;
    private com.teneasyChat.api.core.MetricOuterClass.WorkerMetric metric_;
    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     * @return Whether the metric field is set.
     */
    @java.lang.Override
    public boolean hasMetric() {
      return metric_ != null;
    }
    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     * @return The metric.
     */
    @java.lang.Override
    public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getMetric() {
      return metric_ == null ? com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance() : metric_;
    }
    /**
     * <code>.api.core.WorkerMetric metric = 1;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder getMetricOrBuilder() {
      return metric_ == null ? com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance() : metric_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (metric_ != null) {
        output.writeMessage(1, getMetric());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (metric_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetric());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse other = (com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse) obj;

      if (hasMetric() != other.hasMetric()) return false;
      if (hasMetric()) {
        if (!getMetric()
            .equals(other.getMetric())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMetric()) {
        hash = (37 * hash) + METRIC_FIELD_NUMBER;
        hash = (53 * hash) + getMetric().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.core.QuerySelfResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.core.QuerySelfResponse)
        com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_QuerySelfResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_QuerySelfResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.class, com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.Builder.class);
      }

      // Construct using com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        metric_ = null;
        if (metricBuilder_ != null) {
          metricBuilder_.dispose();
          metricBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.core.MetricOuterClass.internal_static_api_core_QuerySelfResponse_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse getDefaultInstanceForType() {
        return com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse build() {
        com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse buildPartial() {
        com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse result = new com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.metric_ = metricBuilder_ == null
              ? metric_
              : metricBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse) {
          return mergeFrom((com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse other) {
        if (other == com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse.getDefaultInstance()) return this;
        if (other.hasMetric()) {
          mergeMetric(other.getMetric());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMetricFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.teneasyChat.api.core.MetricOuterClass.WorkerMetric metric_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.core.MetricOuterClass.WorkerMetric, com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder, com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder> metricBuilder_;
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       * @return Whether the metric field is set.
       */
      public boolean hasMetric() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       * @return The metric.
       */
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric getMetric() {
        if (metricBuilder_ == null) {
          return metric_ == null ? com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance() : metric_;
        } else {
          return metricBuilder_.getMessage();
        }
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public Builder setMetric(com.teneasyChat.api.core.MetricOuterClass.WorkerMetric value) {
        if (metricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metric_ = value;
        } else {
          metricBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public Builder setMetric(
          com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder builderForValue) {
        if (metricBuilder_ == null) {
          metric_ = builderForValue.build();
        } else {
          metricBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public Builder mergeMetric(com.teneasyChat.api.core.MetricOuterClass.WorkerMetric value) {
        if (metricBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            metric_ != null &&
            metric_ != com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance()) {
            getMetricBuilder().mergeFrom(value);
          } else {
            metric_ = value;
          }
        } else {
          metricBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public Builder clearMetric() {
        bitField0_ = (bitField0_ & ~0x00000001);
        metric_ = null;
        if (metricBuilder_ != null) {
          metricBuilder_.dispose();
          metricBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder getMetricBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMetricFieldBuilder().getBuilder();
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      public com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder getMetricOrBuilder() {
        if (metricBuilder_ != null) {
          return metricBuilder_.getMessageOrBuilder();
        } else {
          return metric_ == null ?
              com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.getDefaultInstance() : metric_;
        }
      }
      /**
       * <code>.api.core.WorkerMetric metric = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.core.MetricOuterClass.WorkerMetric, com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder, com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder> 
          getMetricFieldBuilder() {
        if (metricBuilder_ == null) {
          metricBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.teneasyChat.api.core.MetricOuterClass.WorkerMetric, com.teneasyChat.api.core.MetricOuterClass.WorkerMetric.Builder, com.teneasyChat.api.core.MetricOuterClass.WorkerMetricOrBuilder>(
                  getMetric(),
                  getParentForChildren(),
                  isClean());
          metric_ = null;
        }
        return metricBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.core.QuerySelfResponse)
    }

    // @@protoc_insertion_point(class_scope:api.core.QuerySelfResponse)
    private static final com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse();
    }

    public static com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuerySelfResponse>
        PARSER = new com.google.protobuf.AbstractParser<QuerySelfResponse>() {
      @java.lang.Override
      public QuerySelfResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QuerySelfResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuerySelfResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.core.MetricOuterClass.QuerySelfResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_WorkerMetric_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_WorkerMetric_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_core_QuerySelfResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_core_QuerySelfResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025api/core/metric.proto\022\010api.core\032\020api/o" +
      "ption.proto\032\033google/protobuf/empty.proto" +
      "\032\027validate/validate.proto\"\212\001\n\014WorkerMetr" +
      "ic\022\033\n\023reply_percent_3_min\030\001 \001(\005\022\025\n\rtoday" +
      "_service\030\002 \001(\005\022\032\n\022avg_reply_interval\030\003 \001" +
      "(\005\022\023\n\013transfer_to\030\004 \001(\005\022\025\n\rtransfer_from" +
      "\030\005 \001(\005\";\n\021QuerySelfResponse\022&\n\006metric\030\001 " +
      "\001(\0132\026.api.core.WorkerMetric2\204\001\n\006Metric\022V" +
      "\n\tQuerySelf\022\026.google.protobuf.Empty\032\033.ap" +
      "i.core.QuerySelfResponse\"\024\272\276\031\020\010\260\t\322\014\nquer" +
      "y-self\032\"\272\276\031\036\272\006\006metric\312\014\002\020\004\322\014\rtenant/metr" +
      "icBE\n\030com.teneasyChat.api.coreZ\021wcs/api/" +
      "core;core\272\276\031\024\242\006\004jeff\262\006\n2023-01-14b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.Option.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.teneasyChat.validate.Validate.getDescriptor(),
        });
    internal_static_api_core_WorkerMetric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_core_WorkerMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_WorkerMetric_descriptor,
        new java.lang.String[] { "ReplyPercent3Min", "TodayService", "AvgReplyInterval", "TransferTo", "TransferFrom", });
    internal_static_api_core_QuerySelfResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_core_QuerySelfResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_core_QuerySelfResponse_descriptor,
        new java.lang.String[] { "Metric", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.teneasyChat.api.Option.info);
    registry.add(com.teneasyChat.api.Option.method);
    registry.add(com.teneasyChat.api.Option.service);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.teneasyChat.api.Option.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.teneasyChat.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
