// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_asset.proto

package com.teneasyChat.api.common;

public final class CAsset {
  private CAsset() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code api.common.AssetUploadState}
   */
  public enum AssetUploadState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ASSET_UPLOAD_STATE_UNKNOWN = 0;</code>
     */
    ASSET_UPLOAD_STATE_UNKNOWN(0),
    /**
     * <pre>
     * 上传中
     * </pre>
     *
     * <code>ASSET_UPLOAD_STATE_PUTTING = 1;</code>
     */
    ASSET_UPLOAD_STATE_PUTTING(1),
    /**
     * <pre>
     * 上传完成
     * </pre>
     *
     * <code>ASSET_UPLOAD_STATE_PUT = 2;</code>
     */
    ASSET_UPLOAD_STATE_PUT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ASSET_UPLOAD_STATE_UNKNOWN = 0;</code>
     */
    public static final int ASSET_UPLOAD_STATE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 上传中
     * </pre>
     *
     * <code>ASSET_UPLOAD_STATE_PUTTING = 1;</code>
     */
    public static final int ASSET_UPLOAD_STATE_PUTTING_VALUE = 1;
    /**
     * <pre>
     * 上传完成
     * </pre>
     *
     * <code>ASSET_UPLOAD_STATE_PUT = 2;</code>
     */
    public static final int ASSET_UPLOAD_STATE_PUT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AssetUploadState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AssetUploadState forNumber(int value) {
      switch (value) {
        case 0: return ASSET_UPLOAD_STATE_UNKNOWN;
        case 1: return ASSET_UPLOAD_STATE_PUTTING;
        case 2: return ASSET_UPLOAD_STATE_PUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AssetUploadState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AssetUploadState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AssetUploadState>() {
            public AssetUploadState findValueByNumber(int number) {
              return AssetUploadState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CAsset.getDescriptor().getEnumTypes().get(0);
    }

    private static final AssetUploadState[] VALUES = values();

    public static AssetUploadState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AssetUploadState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.AssetUploadState)
  }

  /**
   * <pre>
   * 文件类型类型 0 ～ 4
   * </pre>
   *
   * Protobuf enum {@code api.common.AssetKind}
   */
  public enum AssetKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ASSET_KIND_NONE = 0;</code>
     */
    ASSET_KIND_NONE(0),
    /**
     * <pre>
     * 商户公共文件
     * </pre>
     *
     * <code>ASSET_KIND_PUBLIC = 1;</code>
     */
    ASSET_KIND_PUBLIC(1),
    /**
     * <pre>
     * 商户私有文件
     * </pre>
     *
     * <code>ASSET_KIND_PRIVATE = 2;</code>
     */
    ASSET_KIND_PRIVATE(2),
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>ASSET_KIND_AVATAR = 3;</code>
     */
    ASSET_KIND_AVATAR(3),
    /**
     * <pre>
     * 会话私有文件
     * </pre>
     *
     * <code>ASSET_KIND_SESSION = 4;</code>
     */
    ASSET_KIND_SESSION(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ASSET_KIND_NONE = 0;</code>
     */
    public static final int ASSET_KIND_NONE_VALUE = 0;
    /**
     * <pre>
     * 商户公共文件
     * </pre>
     *
     * <code>ASSET_KIND_PUBLIC = 1;</code>
     */
    public static final int ASSET_KIND_PUBLIC_VALUE = 1;
    /**
     * <pre>
     * 商户私有文件
     * </pre>
     *
     * <code>ASSET_KIND_PRIVATE = 2;</code>
     */
    public static final int ASSET_KIND_PRIVATE_VALUE = 2;
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>ASSET_KIND_AVATAR = 3;</code>
     */
    public static final int ASSET_KIND_AVATAR_VALUE = 3;
    /**
     * <pre>
     * 会话私有文件
     * </pre>
     *
     * <code>ASSET_KIND_SESSION = 4;</code>
     */
    public static final int ASSET_KIND_SESSION_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AssetKind valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AssetKind forNumber(int value) {
      switch (value) {
        case 0: return ASSET_KIND_NONE;
        case 1: return ASSET_KIND_PUBLIC;
        case 2: return ASSET_KIND_PRIVATE;
        case 3: return ASSET_KIND_AVATAR;
        case 4: return ASSET_KIND_SESSION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AssetKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AssetKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AssetKind>() {
            public AssetKind findValueByNumber(int number) {
              return AssetKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CAsset.getDescriptor().getEnumTypes().get(1);
    }

    private static final AssetKind[] VALUES = values();

    public static AssetKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AssetKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.AssetKind)
  }

  /**
   * <pre>
   * 资源类型 0 ～ 7
   * </pre>
   *
   * Protobuf enum {@code api.common.AssetType}
   */
  public enum AssetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ASSET_TYPE_UNKNOWN = 0;</code>
     */
    ASSET_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 图片 （缩略图复用图片id）
     * </pre>
     *
     * <code>ASSET_TYPE_IMAGE = 1;</code>
     */
    ASSET_TYPE_IMAGE(1),
    /**
     * <pre>
     * 音频
     * </pre>
     *
     * <code>ASSET_TYPE_AUDIO = 2;</code>
     */
    ASSET_TYPE_AUDIO(2),
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>ASSET_TYPE_VIDEO = 3;</code>
     */
    ASSET_TYPE_VIDEO(3),
    /**
     * <pre>
     * 文件
     * </pre>
     *
     * <code>ASSET_TYPE_FILE = 4;</code>
     */
    ASSET_TYPE_FILE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ASSET_TYPE_UNKNOWN = 0;</code>
     */
    public static final int ASSET_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 图片 （缩略图复用图片id）
     * </pre>
     *
     * <code>ASSET_TYPE_IMAGE = 1;</code>
     */
    public static final int ASSET_TYPE_IMAGE_VALUE = 1;
    /**
     * <pre>
     * 音频
     * </pre>
     *
     * <code>ASSET_TYPE_AUDIO = 2;</code>
     */
    public static final int ASSET_TYPE_AUDIO_VALUE = 2;
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>ASSET_TYPE_VIDEO = 3;</code>
     */
    public static final int ASSET_TYPE_VIDEO_VALUE = 3;
    /**
     * <pre>
     * 文件
     * </pre>
     *
     * <code>ASSET_TYPE_FILE = 4;</code>
     */
    public static final int ASSET_TYPE_FILE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AssetType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AssetType forNumber(int value) {
      switch (value) {
        case 0: return ASSET_TYPE_UNKNOWN;
        case 1: return ASSET_TYPE_IMAGE;
        case 2: return ASSET_TYPE_AUDIO;
        case 3: return ASSET_TYPE_VIDEO;
        case 4: return ASSET_TYPE_FILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AssetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AssetType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AssetType>() {
            public AssetType findValueByNumber(int number) {
              return AssetType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CAsset.getDescriptor().getEnumTypes().get(2);
    }

    private static final AssetType[] VALUES = values();

    public static AssetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AssetType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.AssetType)
  }

  /**
   * <pre>
   * 资源用途 0 ～ 15
   * </pre>
   *
   * Protobuf enum {@code api.common.AssetContext}
   */
  public enum AssetContext
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ASSET_CONTEXT_UNKNOWN = 0;</code>
     */
    ASSET_CONTEXT_UNKNOWN(0),
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>ASSET_CONTEXT_MESSAGE = 1;</code>
     */
    ASSET_CONTEXT_MESSAGE(1),
    /**
     * <pre>
     * 朋友圈
     * </pre>
     *
     * <code>ASSET_CONTEXT_MOMENT = 2;</code>
     */
    ASSET_CONTEXT_MOMENT(2),
    /**
     * <pre>
     * 个人/群 头像 二维码 背景图
     * </pre>
     *
     * <code>ASSET_CONTEXT_PROFILE = 3;</code>
     */
    ASSET_CONTEXT_PROFILE(3),
    /**
     * <pre>
     * 收藏夹
     * </pre>
     *
     * <code>ASSET_CONTEXT_FAVORITE = 4;</code>
     */
    ASSET_CONTEXT_FAVORITE(4),
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>ASSET_CONTEXT_EMOJI = 5;</code>
     */
    ASSET_CONTEXT_EMOJI(5),
    /**
     * <pre>
     * 公告
     * </pre>
     *
     * <code>ASSET_CONTEXT_BULLETIN = 6;</code>
     */
    ASSET_CONTEXT_BULLETIN(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ASSET_CONTEXT_UNKNOWN = 0;</code>
     */
    public static final int ASSET_CONTEXT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>ASSET_CONTEXT_MESSAGE = 1;</code>
     */
    public static final int ASSET_CONTEXT_MESSAGE_VALUE = 1;
    /**
     * <pre>
     * 朋友圈
     * </pre>
     *
     * <code>ASSET_CONTEXT_MOMENT = 2;</code>
     */
    public static final int ASSET_CONTEXT_MOMENT_VALUE = 2;
    /**
     * <pre>
     * 个人/群 头像 二维码 背景图
     * </pre>
     *
     * <code>ASSET_CONTEXT_PROFILE = 3;</code>
     */
    public static final int ASSET_CONTEXT_PROFILE_VALUE = 3;
    /**
     * <pre>
     * 收藏夹
     * </pre>
     *
     * <code>ASSET_CONTEXT_FAVORITE = 4;</code>
     */
    public static final int ASSET_CONTEXT_FAVORITE_VALUE = 4;
    /**
     * <pre>
     * 表情
     * </pre>
     *
     * <code>ASSET_CONTEXT_EMOJI = 5;</code>
     */
    public static final int ASSET_CONTEXT_EMOJI_VALUE = 5;
    /**
     * <pre>
     * 公告
     * </pre>
     *
     * <code>ASSET_CONTEXT_BULLETIN = 6;</code>
     */
    public static final int ASSET_CONTEXT_BULLETIN_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AssetContext valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AssetContext forNumber(int value) {
      switch (value) {
        case 0: return ASSET_CONTEXT_UNKNOWN;
        case 1: return ASSET_CONTEXT_MESSAGE;
        case 2: return ASSET_CONTEXT_MOMENT;
        case 3: return ASSET_CONTEXT_PROFILE;
        case 4: return ASSET_CONTEXT_FAVORITE;
        case 5: return ASSET_CONTEXT_EMOJI;
        case 6: return ASSET_CONTEXT_BULLETIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AssetContext>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AssetContext> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AssetContext>() {
            public AssetContext findValueByNumber(int number) {
              return AssetContext.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CAsset.getDescriptor().getEnumTypes().get(3);
    }

    private static final AssetContext[] VALUES = values();

    public static AssetContext valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AssetContext(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.AssetContext)
  }

  public interface AssetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.common.Asset)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * shorturi 短url， 在消息体里表示资源地址
     * </pre>
     *
     * <code>string uri = 1 [(.validate.rules) = { ... }</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <pre>
     * shorturi 短url， 在消息体里表示资源地址
     * </pre>
     *
     * <code>string uri = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();
  }
  /**
   * Protobuf type {@code api.common.Asset}
   */
  public static final class Asset extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.common.Asset)
      AssetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Asset.newBuilder() to construct.
    private Asset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Asset() {
      uri_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Asset();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CAsset.internal_static_api_common_Asset_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.common.CAsset.internal_static_api_common_Asset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.common.CAsset.Asset.class, com.teneasyChat.api.common.CAsset.Asset.Builder.class);
    }

    public static final int URI_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uri_ = "";
    /**
     * <pre>
     * shorturi 短url， 在消息体里表示资源地址
     * </pre>
     *
     * <code>string uri = 1 [(.validate.rules) = { ... }</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * shorturi 短url， 在消息体里表示资源地址
     * </pre>
     *
     * <code>string uri = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.common.CAsset.Asset)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.common.CAsset.Asset other = (com.teneasyChat.api.common.CAsset.Asset) obj;

      if (!getUri()
          .equals(other.getUri())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CAsset.Asset parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.common.CAsset.Asset prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.common.Asset}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.common.Asset)
        com.teneasyChat.api.common.CAsset.AssetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.common.CAsset.internal_static_api_common_Asset_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.common.CAsset.internal_static_api_common_Asset_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.common.CAsset.Asset.class, com.teneasyChat.api.common.CAsset.Asset.Builder.class);
      }

      // Construct using com.teneasyChat.api.common.CAsset.Asset.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uri_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.common.CAsset.internal_static_api_common_Asset_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CAsset.Asset getDefaultInstanceForType() {
        return com.teneasyChat.api.common.CAsset.Asset.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CAsset.Asset build() {
        com.teneasyChat.api.common.CAsset.Asset result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CAsset.Asset buildPartial() {
        com.teneasyChat.api.common.CAsset.Asset result = new com.teneasyChat.api.common.CAsset.Asset(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.common.CAsset.Asset result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uri_ = uri_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.common.CAsset.Asset) {
          return mergeFrom((com.teneasyChat.api.common.CAsset.Asset)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.common.CAsset.Asset other) {
        if (other == com.teneasyChat.api.common.CAsset.Asset.getDefaultInstance()) return this;
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uri_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uri_ = "";
      /**
       * <pre>
       * shorturi 短url， 在消息体里表示资源地址
       * </pre>
       *
       * <code>string uri = 1 [(.validate.rules) = { ... }</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * shorturi 短url， 在消息体里表示资源地址
       * </pre>
       *
       * <code>string uri = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * shorturi 短url， 在消息体里表示资源地址
       * </pre>
       *
       * <code>string uri = 1 [(.validate.rules) = { ... }</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uri_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * shorturi 短url， 在消息体里表示资源地址
       * </pre>
       *
       * <code>string uri = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        uri_ = getDefaultInstance().getUri();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * shorturi 短url， 在消息体里表示资源地址
       * </pre>
       *
       * <code>string uri = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uri_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.common.Asset)
    }

    // @@protoc_insertion_point(class_scope:api.common.Asset)
    private static final com.teneasyChat.api.common.CAsset.Asset DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.common.CAsset.Asset();
    }

    public static com.teneasyChat.api.common.CAsset.Asset getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Asset>
        PARSER = new com.google.protobuf.AbstractParser<Asset>() {
      @java.lang.Override
      public Asset parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Asset> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Asset> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.common.CAsset.Asset getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_common_Asset_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_common_Asset_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030api/common/c_asset.proto\022\napi.common\032\027" +
      "validate/validate.proto\032\037google/protobuf" +
      "/timestamp.proto\"\036\n\005Asset\022\025\n\003uri\030\001 \001(\tB\010" +
      "\372B\005r\003(\200\001*n\n\020AssetUploadState\022\036\n\032ASSET_UP" +
      "LOAD_STATE_UNKNOWN\020\000\022\036\n\032ASSET_UPLOAD_STA" +
      "TE_PUTTING\020\001\022\032\n\026ASSET_UPLOAD_STATE_PUT\020\002" +
      "*~\n\tAssetKind\022\023\n\017ASSET_KIND_NONE\020\000\022\025\n\021AS" +
      "SET_KIND_PUBLIC\020\001\022\026\n\022ASSET_KIND_PRIVATE\020" +
      "\002\022\025\n\021ASSET_KIND_AVATAR\020\003\022\026\n\022ASSET_KIND_S" +
      "ESSION\020\004*z\n\tAssetType\022\026\n\022ASSET_TYPE_UNKN" +
      "OWN\020\000\022\024\n\020ASSET_TYPE_IMAGE\020\001\022\024\n\020ASSET_TYP" +
      "E_AUDIO\020\002\022\024\n\020ASSET_TYPE_VIDEO\020\003\022\023\n\017ASSET" +
      "_TYPE_FILE\020\004*\312\001\n\014AssetContext\022\031\n\025ASSET_C" +
      "ONTEXT_UNKNOWN\020\000\022\031\n\025ASSET_CONTEXT_MESSAG" +
      "E\020\001\022\030\n\024ASSET_CONTEXT_MOMENT\020\002\022\031\n\025ASSET_C" +
      "ONTEXT_PROFILE\020\003\022\032\n\026ASSET_CONTEXT_FAVORI" +
      "TE\020\004\022\027\n\023ASSET_CONTEXT_EMOJI\020\005\022\032\n\026ASSET_C" +
      "ONTEXT_BULLETIN\020\006B<\n\032com.teneasyChat.api" +
      ".commonZ\025wcs/api/common;common\272\002\006Commonb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_api_common_Asset_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_common_Asset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_common_Asset_descriptor,
        new java.lang.String[] { "Uri", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
