// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_device.proto

package com.teneasyChat.api.common;

public final class CDevice {
  private CDevice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code api.common.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 系统平台
     * </pre>
     *
     * <code>System = 0;</code>
     */
    System(0),
    /**
     * <pre>
     * 桌面设备
     * </pre>
     *
     * <code>Desktop = 1;</code>
     */
    Desktop(1),
    /**
     * <pre>
     * IOS
     * </pre>
     *
     * <code>Ios = 2;</code>
     */
    Ios(2),
    /**
     * <pre>
     * Android
     * </pre>
     *
     * <code>Android = 3;</code>
     */
    Android(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 系统平台
     * </pre>
     *
     * <code>System = 0;</code>
     */
    public static final int System_VALUE = 0;
    /**
     * <pre>
     * 桌面设备
     * </pre>
     *
     * <code>Desktop = 1;</code>
     */
    public static final int Desktop_VALUE = 1;
    /**
     * <pre>
     * IOS
     * </pre>
     *
     * <code>Ios = 2;</code>
     */
    public static final int Ios_VALUE = 2;
    /**
     * <pre>
     * Android
     * </pre>
     *
     * <code>Android = 3;</code>
     */
    public static final int Android_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DeviceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DeviceType forNumber(int value) {
      switch (value) {
        case 0: return System;
        case 1: return Desktop;
        case 2: return Ios;
        case 3: return Android;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeviceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CDevice.getDescriptor().getEnumTypes().get(0);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DeviceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.DeviceType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031api/common/c_device.proto\022\napi.common*" +
      ";\n\nDeviceType\022\n\n\006System\020\000\022\013\n\007Desktop\020\001\022\007" +
      "\n\003Ios\020\002\022\013\n\007Android\020\003B<\n\032com.teneasyChat." +
      "api.commonZ\025wcs/api/common;common\272\002\006Comm" +
      "onb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
