// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_entry.proto

package com.teneasyChat.api.common;

public final class CEntry {
  private CEntry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code api.common.TransportType}
   */
  public enum TransportType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRANSPORT_HTTP = 0;</code>
     */
    TRANSPORT_HTTP(0),
    /**
     * <code>TRANSPORT_HTTPS = 3;</code>
     */
    TRANSPORT_HTTPS(3),
    /**
     * <code>TRANSPORT_H2C = 5;</code>
     */
    TRANSPORT_H2C(5),
    /**
     * <code>TRANSPORT_HTTP3 = 30;</code>
     */
    TRANSPORT_HTTP3(30),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TRANSPORT_HTTP = 0;</code>
     */
    public static final int TRANSPORT_HTTP_VALUE = 0;
    /**
     * <code>TRANSPORT_HTTPS = 3;</code>
     */
    public static final int TRANSPORT_HTTPS_VALUE = 3;
    /**
     * <code>TRANSPORT_H2C = 5;</code>
     */
    public static final int TRANSPORT_H2C_VALUE = 5;
    /**
     * <code>TRANSPORT_HTTP3 = 30;</code>
     */
    public static final int TRANSPORT_HTTP3_VALUE = 30;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransportType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TransportType forNumber(int value) {
      switch (value) {
        case 0: return TRANSPORT_HTTP;
        case 3: return TRANSPORT_HTTPS;
        case 5: return TRANSPORT_H2C;
        case 30: return TRANSPORT_HTTP3;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransportType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransportType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransportType>() {
            public TransportType findValueByNumber(int number) {
              return TransportType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CEntry.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransportType[] VALUES = values();

    public static TransportType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransportType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.TransportType)
  }

  /**
   * Protobuf enum {@code api.common.AddressType}
   */
  public enum AddressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 域名
     * </pre>
     *
     * <code>ADDRES_DOMAIN = 0;</code>
     */
    ADDRES_DOMAIN(0),
    /**
     * <pre>
     * ip4
     * </pre>
     *
     * <code>ADDRES_IPV4 = 1;</code>
     */
    ADDRES_IPV4(1),
    /**
     * <pre>
     * ip6
     * </pre>
     *
     * <code>addres_ipv6 = 2;</code>
     */
    addres_ipv6(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 域名
     * </pre>
     *
     * <code>ADDRES_DOMAIN = 0;</code>
     */
    public static final int ADDRES_DOMAIN_VALUE = 0;
    /**
     * <pre>
     * ip4
     * </pre>
     *
     * <code>ADDRES_IPV4 = 1;</code>
     */
    public static final int ADDRES_IPV4_VALUE = 1;
    /**
     * <pre>
     * ip6
     * </pre>
     *
     * <code>addres_ipv6 = 2;</code>
     */
    public static final int addres_ipv6_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AddressType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AddressType forNumber(int value) {
      switch (value) {
        case 0: return ADDRES_DOMAIN;
        case 1: return ADDRES_IPV4;
        case 2: return addres_ipv6;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AddressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AddressType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AddressType>() {
            public AddressType findValueByNumber(int number) {
              return AddressType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CEntry.getDescriptor().getEnumTypes().get(1);
    }

    private static final AddressType[] VALUES = values();

    public static AddressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AddressType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.AddressType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030api/common/c_entry.proto\022\napi.common\032\031" +
      "api/common/c_device.proto\032\037google/protob" +
      "uf/timestamp.proto*`\n\rTransportType\022\022\n\016T" +
      "RANSPORT_HTTP\020\000\022\023\n\017TRANSPORT_HTTPS\020\003\022\021\n\r" +
      "TRANSPORT_H2C\020\005\022\023\n\017TRANSPORT_HTTP3\020\036*B\n\013" +
      "AddressType\022\021\n\rADDRES_DOMAIN\020\000\022\017\n\013ADDRES" +
      "_IPV4\020\001\022\017\n\013addres_ipv6\020\002B3\n\032com.teneasyC" +
      "hat.api.commonZ\025wcs/api/common;commonb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.teneasyChat.api.common.CDevice.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    com.teneasyChat.api.common.CDevice.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
