// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_note.proto

package com.teneasyChat.api.common;

public final class CNote {
  private CNote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.common.Note)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.api.common.Message raw = 1;</code>
     * @return Whether the raw field is set.
     */
    boolean hasRaw();
    /**
     * <code>.api.common.Message raw = 1;</code>
     * @return The raw.
     */
    com.teneasyChat.api.common.CMessage.Message getRaw();
    /**
     * <code>.api.common.Message raw = 1;</code>
     */
    com.teneasyChat.api.common.CMessage.MessageOrBuilder getRawOrBuilder();

    /**
     * <pre>
     * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code api.common.Note}
   */
  public static final class Note extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.common.Note)
      NoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Note.newBuilder() to construct.
    private Note(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Note() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Note();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CNote.internal_static_api_common_Note_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.common.CNote.internal_static_api_common_Note_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.common.CNote.Note.class, com.teneasyChat.api.common.CNote.Note.Builder.class);
    }

    public static final int RAW_FIELD_NUMBER = 1;
    private com.teneasyChat.api.common.CMessage.Message raw_;
    /**
     * <code>.api.common.Message raw = 1;</code>
     * @return Whether the raw field is set.
     */
    @java.lang.Override
    public boolean hasRaw() {
      return raw_ != null;
    }
    /**
     * <code>.api.common.Message raw = 1;</code>
     * @return The raw.
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CMessage.Message getRaw() {
      return raw_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : raw_;
    }
    /**
     * <code>.api.common.Message raw = 1;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CMessage.MessageOrBuilder getRawOrBuilder() {
      return raw_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : raw_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (raw_ != null) {
        output.writeMessage(1, getRaw());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (raw_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRaw());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.common.CNote.Note)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.common.CNote.Note other = (com.teneasyChat.api.common.CNote.Note) obj;

      if (hasRaw() != other.hasRaw()) return false;
      if (hasRaw()) {
        if (!getRaw()
            .equals(other.getRaw())) return false;
      }
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRaw()) {
        hash = (37 * hash) + RAW_FIELD_NUMBER;
        hash = (53 * hash) + getRaw().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Note parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Note parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Note parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.common.CNote.Note prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.common.Note}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.common.Note)
        com.teneasyChat.api.common.CNote.NoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Note_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Note_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.common.CNote.Note.class, com.teneasyChat.api.common.CNote.Note.Builder.class);
      }

      // Construct using com.teneasyChat.api.common.CNote.Note.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        raw_ = null;
        if (rawBuilder_ != null) {
          rawBuilder_.dispose();
          rawBuilder_ = null;
        }
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Note_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Note getDefaultInstanceForType() {
        return com.teneasyChat.api.common.CNote.Note.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Note build() {
        com.teneasyChat.api.common.CNote.Note result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Note buildPartial() {
        com.teneasyChat.api.common.CNote.Note result = new com.teneasyChat.api.common.CNote.Note(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.common.CNote.Note result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.raw_ = rawBuilder_ == null
              ? raw_
              : rawBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.common.CNote.Note) {
          return mergeFrom((com.teneasyChat.api.common.CNote.Note)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.common.CNote.Note other) {
        if (other == com.teneasyChat.api.common.CNote.Note.getDefaultInstance()) return this;
        if (other.hasRaw()) {
          mergeRaw(other.getRaw());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getRawFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.teneasyChat.api.common.CMessage.Message raw_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder> rawBuilder_;
      /**
       * <code>.api.common.Message raw = 1;</code>
       * @return Whether the raw field is set.
       */
      public boolean hasRaw() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       * @return The raw.
       */
      public com.teneasyChat.api.common.CMessage.Message getRaw() {
        if (rawBuilder_ == null) {
          return raw_ == null ? com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : raw_;
        } else {
          return rawBuilder_.getMessage();
        }
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public Builder setRaw(com.teneasyChat.api.common.CMessage.Message value) {
        if (rawBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          raw_ = value;
        } else {
          rawBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public Builder setRaw(
          com.teneasyChat.api.common.CMessage.Message.Builder builderForValue) {
        if (rawBuilder_ == null) {
          raw_ = builderForValue.build();
        } else {
          rawBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public Builder mergeRaw(com.teneasyChat.api.common.CMessage.Message value) {
        if (rawBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            raw_ != null &&
            raw_ != com.teneasyChat.api.common.CMessage.Message.getDefaultInstance()) {
            getRawBuilder().mergeFrom(value);
          } else {
            raw_ = value;
          }
        } else {
          rawBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public Builder clearRaw() {
        bitField0_ = (bitField0_ & ~0x00000001);
        raw_ = null;
        if (rawBuilder_ != null) {
          rawBuilder_.dispose();
          rawBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public com.teneasyChat.api.common.CMessage.Message.Builder getRawBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRawFieldBuilder().getBuilder();
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      public com.teneasyChat.api.common.CMessage.MessageOrBuilder getRawOrBuilder() {
        if (rawBuilder_ != null) {
          return rawBuilder_.getMessageOrBuilder();
        } else {
          return raw_ == null ?
              com.teneasyChat.api.common.CMessage.Message.getDefaultInstance() : raw_;
        }
      }
      /**
       * <code>.api.common.Message raw = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder> 
          getRawFieldBuilder() {
        if (rawBuilder_ == null) {
          rawBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.teneasyChat.api.common.CMessage.Message, com.teneasyChat.api.common.CMessage.Message.Builder, com.teneasyChat.api.common.CMessage.MessageOrBuilder>(
                  getRaw(),
                  getParentForChildren(),
                  isClean());
          raw_ = null;
        }
        return rawBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作客服名称: 业务需求 使用创建时 客服名称, 避免客服删除时找不到对应名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.common.Note)
    }

    // @@protoc_insertion_point(class_scope:api.common.Note)
    private static final com.teneasyChat.api.common.CNote.Note DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.common.CNote.Note();
    }

    public static com.teneasyChat.api.common.CNote.Note getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Note>
        PARSER = new com.google.protobuf.AbstractParser<Note>() {
      @java.lang.Override
      public Note parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Note> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Note> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.common.CNote.Note getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NotesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api.common.Notes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    int getNotesCount();
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    boolean containsNotes(
        java.lang.String key);
    /**
     * Use {@link #getNotesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note>
    getNotes();
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note>
    getNotesMap();
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    /* nullable */
com.teneasyChat.api.common.CNote.Note getNotesOrDefault(
        java.lang.String key,
        /* nullable */
com.teneasyChat.api.common.CNote.Note defaultValue);
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    com.teneasyChat.api.common.CNote.Note getNotesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code api.common.Notes}
   */
  public static final class Notes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api.common.Notes)
      NotesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notes.newBuilder() to construct.
    private Notes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notes() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Notes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetNotes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.teneasyChat.api.common.CNote.Notes.class, com.teneasyChat.api.common.CNote.Notes.Builder.class);
    }

    public static final int NOTES_FIELD_NUMBER = 1;
    private static final class NotesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.teneasyChat.api.common.CNote.Note> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.teneasyChat.api.common.CNote.Note>newDefaultInstance(
                  com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_NotesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.teneasyChat.api.common.CNote.Note.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.teneasyChat.api.common.CNote.Note> notes_;
    private com.google.protobuf.MapField<java.lang.String, com.teneasyChat.api.common.CNote.Note>
    internalGetNotes() {
      if (notes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NotesDefaultEntryHolder.defaultEntry);
      }
      return notes_;
    }
    public int getNotesCount() {
      return internalGetNotes().getMap().size();
    }
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    @java.lang.Override
    public boolean containsNotes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetNotes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNotesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> getNotes() {
      return getNotesMap();
    }
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> getNotesMap() {
      return internalGetNotes().getMap();
    }
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.teneasyChat.api.common.CNote.Note getNotesOrDefault(
        java.lang.String key,
        /* nullable */
com.teneasyChat.api.common.CNote.Note defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> map =
          internalGetNotes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
     * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
     * </pre>
     *
     * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
     */
    @java.lang.Override
    public com.teneasyChat.api.common.CNote.Note getNotesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> map =
          internalGetNotes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetNotes(),
          NotesDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.teneasyChat.api.common.CNote.Note> entry
           : internalGetNotes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.teneasyChat.api.common.CNote.Note>
        notes__ = NotesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, notes__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.teneasyChat.api.common.CNote.Notes)) {
        return super.equals(obj);
      }
      com.teneasyChat.api.common.CNote.Notes other = (com.teneasyChat.api.common.CNote.Notes) obj;

      if (!internalGetNotes().equals(
          other.internalGetNotes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetNotes().getMap().isEmpty()) {
        hash = (37 * hash) + NOTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNotes().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.teneasyChat.api.common.CNote.Notes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.teneasyChat.api.common.CNote.Notes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api.common.Notes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api.common.Notes)
        com.teneasyChat.api.common.CNote.NotesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetNotes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableNotes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.teneasyChat.api.common.CNote.Notes.class, com.teneasyChat.api.common.CNote.Notes.Builder.class);
      }

      // Construct using com.teneasyChat.api.common.CNote.Notes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableNotes().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.teneasyChat.api.common.CNote.internal_static_api_common_Notes_descriptor;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Notes getDefaultInstanceForType() {
        return com.teneasyChat.api.common.CNote.Notes.getDefaultInstance();
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Notes build() {
        com.teneasyChat.api.common.CNote.Notes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Notes buildPartial() {
        com.teneasyChat.api.common.CNote.Notes result = new com.teneasyChat.api.common.CNote.Notes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.teneasyChat.api.common.CNote.Notes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.notes_ = internalGetNotes();
          result.notes_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.teneasyChat.api.common.CNote.Notes) {
          return mergeFrom((com.teneasyChat.api.common.CNote.Notes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.teneasyChat.api.common.CNote.Notes other) {
        if (other == com.teneasyChat.api.common.CNote.Notes.getDefaultInstance()) return this;
        internalGetMutableNotes().mergeFrom(
            other.internalGetNotes());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, com.teneasyChat.api.common.CNote.Note>
                notes__ = input.readMessage(
                    NotesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableNotes().getMutableMap().put(
                    notes__.getKey(), notes__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.teneasyChat.api.common.CNote.Note> notes_;
      private com.google.protobuf.MapField<java.lang.String, com.teneasyChat.api.common.CNote.Note>
          internalGetNotes() {
        if (notes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NotesDefaultEntryHolder.defaultEntry);
        }
        return notes_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.teneasyChat.api.common.CNote.Note>
          internalGetMutableNotes() {
        if (notes_ == null) {
          notes_ = com.google.protobuf.MapField.newMapField(
              NotesDefaultEntryHolder.defaultEntry);
        }
        if (!notes_.isMutable()) {
          notes_ = notes_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return notes_;
      }
      public int getNotesCount() {
        return internalGetNotes().getMap().size();
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      @java.lang.Override
      public boolean containsNotes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetNotes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNotesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> getNotes() {
        return getNotesMap();
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> getNotesMap() {
        return internalGetNotes().getMap();
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.teneasyChat.api.common.CNote.Note getNotesOrDefault(
          java.lang.String key,
          /* nullable */
com.teneasyChat.api.common.CNote.Note defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> map =
            internalGetNotes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      @java.lang.Override
      public com.teneasyChat.api.common.CNote.Note getNotesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> map =
            internalGetNotes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearNotes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableNotes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      public Builder removeNotes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableNotes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note>
          getMutableNotes() {
        bitField0_ |= 0x00000001;
        return internalGetMutableNotes().getMutableMap();
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      public Builder putNotes(
          java.lang.String key,
          com.teneasyChat.api.common.CNote.Note value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableNotes().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * k: hex(秒级unix时间&lt;&lt;32+客服id, 36), 即单个客服1秒内仅能创建一条备注
       * strconv.FormatInt 原因: 减少作为pson存储时, k的长度体积
       * </pre>
       *
       * <code>map&lt;string, .api.common.Note&gt; notes = 1;</code>
       */
      public Builder putAllNotes(
          java.util.Map<java.lang.String, com.teneasyChat.api.common.CNote.Note> values) {
        internalGetMutableNotes().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api.common.Notes)
    }

    // @@protoc_insertion_point(class_scope:api.common.Notes)
    private static final com.teneasyChat.api.common.CNote.Notes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.teneasyChat.api.common.CNote.Notes();
    }

    public static com.teneasyChat.api.common.CNote.Notes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Notes>
        PARSER = new com.google.protobuf.AbstractParser<Notes>() {
      @java.lang.Override
      public Notes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Notes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.teneasyChat.api.common.CNote.Notes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_common_Note_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_common_Note_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_common_Notes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_common_Notes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_common_Notes_NotesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_common_Notes_NotesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027api/common/c_note.proto\022\napi.common\032\037g" +
      "oogle/protobuf/timestamp.proto\032\032api/comm" +
      "on/c_message.proto\032\036google/protobuf/wrap" +
      "pers.proto\"6\n\004Note\022 \n\003raw\030\001 \001(\0132\023.api.co" +
      "mmon.Message\022\014\n\004name\030\002 \001(\t\"t\n\005Notes\022+\n\005n" +
      "otes\030\001 \003(\0132\034.api.common.Notes.NotesEntry" +
      "\032>\n\nNotesEntry\022\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001" +
      "(\0132\020.api.common.Note:\0028\001B3\n\032com.teneasyC" +
      "hat.api.commonZ\025wcs/api/common;commonb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.teneasyChat.api.common.CMessage.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_api_common_Note_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_common_Note_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_common_Note_descriptor,
        new java.lang.String[] { "Raw", "Name", });
    internal_static_api_common_Notes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_common_Notes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_common_Notes_descriptor,
        new java.lang.String[] { "Notes", });
    internal_static_api_common_Notes_NotesEntry_descriptor =
      internal_static_api_common_Notes_descriptor.getNestedTypes().get(0);
    internal_static_api_common_Notes_NotesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_common_Notes_NotesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.teneasyChat.api.common.CMessage.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
