// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_operate.proto

package com.teneasyChat.api.common;

public final class COperate {
  private COperate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code api.common.Operate}
   */
  public enum Operate
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Get = 0;</code>
     */
    Get(0),
    /**
     * <code>Set = 1;</code>
     */
    Set(1),
    /**
     * <code>UnSet = 2;</code>
     */
    UnSet(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Get = 0;</code>
     */
    public static final int Get_VALUE = 0;
    /**
     * <code>Set = 1;</code>
     */
    public static final int Set_VALUE = 1;
    /**
     * <code>UnSet = 2;</code>
     */
    public static final int UnSet_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operate valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Operate forNumber(int value) {
      switch (value) {
        case 0: return Get;
        case 1: return Set;
        case 2: return UnSet;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operate>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operate> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operate>() {
            public Operate findValueByNumber(int number) {
              return Operate.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.COperate.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operate[] VALUES = values();

    public static Operate valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operate(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.Operate)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032api/common/c_operate.proto\022\napi.common" +
      "*&\n\007Operate\022\007\n\003Get\020\000\022\007\n\003Set\020\001\022\t\n\005UnSet\020\002" +
      "B<\n\032com.teneasyChat.api.commonZ\025wcs/api/" +
      "common;common\272\002\006Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
