// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/c_qr_code.proto

package com.teneasyChat.api.common;

public final class CQrCode {
  private CQrCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 二维码类别: QRCode(CAT)egory
   * </pre>
   *
   * Protobuf enum {@code api.common.QRCodeCAT}
   */
  public enum QRCodeCAT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QR_CODE_CAT_UNKNOWN = 0;</code>
     */
    QR_CODE_CAT_UNKNOWN(0),
    /**
     * <pre>
     * 用户名片, 包含 用户ID, AssetID, Name 信息
     * </pre>
     *
     * <code>QR_CODE_CAT_USER_CARD = 1;</code>
     */
    QR_CODE_CAT_USER_CARD(1),
    /**
     * <pre>
     * 用户精简名片, 包含 用户ID, AssetID, Name 信息, 每个字段 部分隐藏
     * </pre>
     *
     * <code>QR_CODE_CAT_USER_CARD_LITE = 2;</code>
     */
    QR_CODE_CAT_USER_CARD_LITE(2),
    /**
     * <pre>
     * 群名片, 包含 群ID, AssetID, Name 信息
     * </pre>
     *
     * <code>QR_CODE_CAT_GROUP_CARD = 3;</code>
     */
    QR_CODE_CAT_GROUP_CARD(3),
    /**
     * <pre>
     * 群精简名片, 包含 群ID, AssetID, Name 信息, 每个字段 部分隐藏
     * </pre>
     *
     * <code>QR_CODE_CAT_GROUP_CARD_LITE = 4;</code>
     */
    QR_CODE_CAT_GROUP_CARD_LITE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>QR_CODE_CAT_UNKNOWN = 0;</code>
     */
    public static final int QR_CODE_CAT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 用户名片, 包含 用户ID, AssetID, Name 信息
     * </pre>
     *
     * <code>QR_CODE_CAT_USER_CARD = 1;</code>
     */
    public static final int QR_CODE_CAT_USER_CARD_VALUE = 1;
    /**
     * <pre>
     * 用户精简名片, 包含 用户ID, AssetID, Name 信息, 每个字段 部分隐藏
     * </pre>
     *
     * <code>QR_CODE_CAT_USER_CARD_LITE = 2;</code>
     */
    public static final int QR_CODE_CAT_USER_CARD_LITE_VALUE = 2;
    /**
     * <pre>
     * 群名片, 包含 群ID, AssetID, Name 信息
     * </pre>
     *
     * <code>QR_CODE_CAT_GROUP_CARD = 3;</code>
     */
    public static final int QR_CODE_CAT_GROUP_CARD_VALUE = 3;
    /**
     * <pre>
     * 群精简名片, 包含 群ID, AssetID, Name 信息, 每个字段 部分隐藏
     * </pre>
     *
     * <code>QR_CODE_CAT_GROUP_CARD_LITE = 4;</code>
     */
    public static final int QR_CODE_CAT_GROUP_CARD_LITE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static QRCodeCAT valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static QRCodeCAT forNumber(int value) {
      switch (value) {
        case 0: return QR_CODE_CAT_UNKNOWN;
        case 1: return QR_CODE_CAT_USER_CARD;
        case 2: return QR_CODE_CAT_USER_CARD_LITE;
        case 3: return QR_CODE_CAT_GROUP_CARD;
        case 4: return QR_CODE_CAT_GROUP_CARD_LITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<QRCodeCAT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        QRCodeCAT> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QRCodeCAT>() {
            public QRCodeCAT findValueByNumber(int number) {
              return QRCodeCAT.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CQrCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final QRCodeCAT[] VALUES = values();

    public static QRCodeCAT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private QRCodeCAT(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.QRCodeCAT)
  }

  /**
   * <pre>
   * 二维码类型: 动态码,静态码
   * </pre>
   *
   * Protobuf enum {@code api.common.QRCodeType}
   */
  public enum QRCodeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QR_CODE_TYPE_UNKNOWN = 0;</code>
     */
    QR_CODE_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 静态码
     * </pre>
     *
     * <code>QR_CODE_TYPE_STATIC = 1;</code>
     */
    QR_CODE_TYPE_STATIC(1),
    /**
     * <pre>
     * 动态码
     * </pre>
     *
     * <code>QR_CODE_TYPE_DYNAMIC = 2;</code>
     */
    QR_CODE_TYPE_DYNAMIC(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>QR_CODE_TYPE_UNKNOWN = 0;</code>
     */
    public static final int QR_CODE_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 静态码
     * </pre>
     *
     * <code>QR_CODE_TYPE_STATIC = 1;</code>
     */
    public static final int QR_CODE_TYPE_STATIC_VALUE = 1;
    /**
     * <pre>
     * 动态码
     * </pre>
     *
     * <code>QR_CODE_TYPE_DYNAMIC = 2;</code>
     */
    public static final int QR_CODE_TYPE_DYNAMIC_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static QRCodeType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static QRCodeType forNumber(int value) {
      switch (value) {
        case 0: return QR_CODE_TYPE_UNKNOWN;
        case 1: return QR_CODE_TYPE_STATIC;
        case 2: return QR_CODE_TYPE_DYNAMIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<QRCodeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        QRCodeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QRCodeType>() {
            public QRCodeType findValueByNumber(int number) {
              return QRCodeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.teneasyChat.api.common.CQrCode.getDescriptor().getEnumTypes().get(1);
    }

    private static final QRCodeType[] VALUES = values();

    public static QRCodeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private QRCodeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:api.common.QRCodeType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032api/common/c_qr_code.proto\022\napi.common" +
      "*\234\001\n\tQRCodeCAT\022\027\n\023QR_CODE_CAT_UNKNOWN\020\000\022" +
      "\031\n\025QR_CODE_CAT_USER_CARD\020\001\022\036\n\032QR_CODE_CA" +
      "T_USER_CARD_LITE\020\002\022\032\n\026QR_CODE_CAT_GROUP_" +
      "CARD\020\003\022\037\n\033QR_CODE_CAT_GROUP_CARD_LITE\020\004*" +
      "Y\n\nQRCodeType\022\030\n\024QR_CODE_TYPE_UNKNOWN\020\000\022" +
      "\027\n\023QR_CODE_TYPE_STATIC\020\001\022\030\n\024QR_CODE_TYPE" +
      "_DYNAMIC\020\002B<\n\032com.teneasyChat.api.common" +
      "Z\025wcs/api/common;common\272\002\006Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
